### ISSUE TITLE
Seria mejor usar Variables y no codigo duro

### ISSUE THREAD

**Issue by chepecarlos** [ramun9533/RA#1]
Al momento de programar en bueno parametizar o crear variables para guardar valores en el futuro; evitando recordar que esta conectado en el pin numero 2 por dar un ejemplo 

**Malo**
```c++
  pinMode(2, INPUT);
  arranque = digitalRead(2);

```
**Bueno***
```c++
  int PinArranque = 2;
  pinMode(PinArranque, INPUT);
  arranque = digitalRead(PinArranque);
```

**hardcoding** es la técnica donde se escibe valores  dentro de código que se repite con frecuencia y que puede ocacionar problemas en el futuro.

Empieza  a quitar todo el **HardCoding**, te parece buena idea?

**Comment by ramun9533** [comment]
Esto lo hago en "setup" o loop" ?

**Comment by chepecarlos** [comment]
Si crear una manzana tienes que usarla en todo el codigo :)

**Comment by chepecarlos** [comment]
Como las mejoras ya fueron echas por ti, deberias cerrar el problema o issues conel boton **close with comment**

**Comment by ramun9533** [comment]
Se hace corrección de problema.
