### ISSUE TITLE
Agregar Diagrama del proyecto

### ISSUE THREAD

**Issue by chepecarlos** [ramun9533/RA#2]
Seria buena idea crear un folder y agregar el diseño del circuito, para que sea mas sensillo como funciona y el futuro entiendas como armarlo o mejorarlo  

Recomiendo usas [Fritzing](https://github.com/fritzing/fritzing-app/releases) para modelar los diagramas

**Comment by ramun9533** [comment]
Ya se agregó el diegrama que pediste, pero falta el archivo README

**Comment by ramun9533** [comment]
Ya se agregó diagrama.
